### ISSUE TITLE
[ArchitectureHandbook] Hoàn thành tài liệu

### ISSUE THREAD

**Issue by tuananhlai** [biennd279/OOAD#6]

**Comment by biennd279** [comment]
https://github.com/biennd279/OOAD/commit/59319dee0b83592d5bd1d8f80b9a05d6ca6465d9

**Comment by tuananhlai** [comment]
Có vấn đề gì mà phải reopen à m?

**Comment by biennd279** [comment]
Bảng cuối thiếu

**Comment by tuananhlai** [comment]
@huyenlovemath bổ sung bảng mapping từ phần tử thiết kế sang process nhé.
